version: "3.8"

services:
  study-database:
    container_name: study-database
    image: immunogen/study-database
    environment:
      - MYSQL_DATABASE=mugeon
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - ./infra/database/config:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    restart: always
