version: "3.8"
services:
  cstudy-database:
    container_name: study-database
    build:
      dockerfile: Dockerfile
      context: ./infra/database
    image: immunogen/study-database 
    environment:
      - MYSQL_DATABASE=CStudy
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - ./infra/database/config:/etc/mysql/conf.d
    ports:
      - "3306:3306"
