version: "3.8"
services:
  study-database:
    container_name: study-database
    build:
      dockerfile: Dockerfile
      context: ./infra/database
    image: immunogen/study-database
    environment:
      - MYSQL_DATABASE=CStudy
      - MYSQL_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./infra/database/config:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    restart: always