spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password: 4167
    driver-class-name: org.h2.Driver
    hikari:
      connection-timeout: 100000
      validation-timeout: 100000
      minimum-idle: 5
      max-lifetime: 180000
      maximum-pool-size: 10
      idle-timeout: 90000
  sql:
    init:
      mode: always
      schema-locations: classpath*:schema.sql
      data-locations: classpath*:data.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    hibernate:
      ddl-auto: create
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    async:
      request-timeout: 60000
  devtools:
    livereload:
      enabled: true



mybatis:
  mapper-locations: classpath:mappers/*.xml



management:
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
  endpoint:
    health:
      show-details: always
#      show-components: always
  endpoints:
    web:
      exposure:
        include: "*"




#  server:
#    port: 9292

# info에 추가하고 싶은 정보
info:
  app:
    name: hello-actuator
    company: yh

