spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #       show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    defer-datasource-initialization: true
  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5
  sql:
    init:
      mode: always

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

server:
  port: 8888