---
spring:
  config:
    activate:
      on-profile: set1
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: "*"

---
spring:
  config:
    activate:
      on-profile: set2
server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
        include: "*"
