spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
#  data:
#    rest:
#      base-path: /api
#      detection-strategy: annotated
logging:
  level:
    org.hibernate.SQL: debug
