version: "3.8"
services:
  CStudy-database:
    container_name: study-database
    build:
      dockerfile: ./database/Dockerfile
      context: ./database
    image: immunogen/study-database
    environment:
      - MYSQL_DATABASE=CStudy
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - ./database/config:/etc/mysql/conf.d
    ports:
      - "3306:3306"
